'use client'
import { Box, Card, Container, Grid, Typography } from "@mui/material"
import { useTheme } from "@mui/material/styles";
import { Award, BarChart3, Brain, Briefcase, Lock, Rocket, TrendingUp, Users } from "lucide-react";

export default function FeatureSection() {
      const theme = useTheme();

    return (
             <Box className="wow animate__animated animate__fadeInUp" data-wow-once="true" suppressHydrationWarning sx={{ py: { xs: 4, sm: 4, md: 6 }, position: 'relative', zIndex: 10 }}>
               <Container maxWidth="xl" sx={{ px: { xs: 2, sm: 3 } }}>
                 <Box sx={{ textAlign: 'center', mb: { xs: 6, sm: 8 } }}>
                   <Typography
                     variant="h2"
                     sx={{
                       fontSize: { xs: '1.875rem', sm: '2.5rem', md: '3rem', lg: '3.5rem' },
                       fontWeight: 'bold',
                       color: theme.palette.primary.main, // Uses theme Orange
                       mb: 2,
                       px: { xs: 2, sm: 0 },
                     }}
                   >
                     Why Choose SkillSense?
                   </Typography>
                   <Typography
                     variant="h5"
                     sx={{
                       color: theme.palette.secondary.main, // Uses theme Aqua Blue
                       maxWidth: '800px',
                       fontWeight: 300,
                       mx: 'auto',
                       fontSize: { xs: '1rem', sm: '1.125rem', md: '1.10rem' },
                       px: { xs: 2, sm: 0 },
                     }}
                   >
                     Everything you need to ace your interviews and build a successful career
                   </Typography>
                 </Box>
                 <Grid  container spacing={{ xs: 3, sm: 4 }}>
                   {[
                     {
                       icon: Brain,
                       title: 'AI-Powered Questions',
                       description: 'Get realistic interview questions generated by advanced AI tailored to your skill level'
                     },
                     {
                       icon: BarChart3,
                       title: 'Detailed Feedback',
                       description: 'Receive comprehensive analysis of your performance with actionable insights'
                     },
                     {
                       icon: Users,
                       title: 'Company Integration',
                       description: 'Companies can post jobs, evaluate candidates, and manage hiring pipeline'
                     },
                     {
                       icon: Lock,
                       title: 'Secure & Private',
                       description: 'Enterprise-grade security with encrypted video recording and data protection'
                     },
                     {
                       icon: Award,
                       title: 'Skill Certification',
                       description: 'Earn verified certificates to showcase your interview readiness'
                     },
                     {
                       icon: Rocket,
                       title: 'Career Growth',
                       description: 'Access learning paths and resources to continuously improve your skills'
                     },
                     {
                       icon: TrendingUp,
                       title: 'Performance Tracking',
                       description: 'Monitor your progress with detailed analytics and improvement metrics'
                     },
                     {
                       icon: Briefcase,
                       title: 'Job Opportunities',
                       description: 'Connect with top companies actively hiring through our platform'
                     }
                   ].map((feature, idx) => {
                     const Icon = feature.icon
                     const animationDirection = idx < 4 ? 'fadeInLeft' : 'fadeInRight';
                     const delay = (idx % 4) * 0.1; 

                     return (
                       <Grid className={`wow animate__animated animate__${animationDirection}`} data-wow-once="true"
               data-wow-delay={`${delay}s`} size={{ xs: 12, sm: 6, md: 3 }} key={idx} suppressHydrationWarning>
                         <Card
                           sx={{
                             background: 'background.paper',
                             borderRadius: 3,
                             p: { xs: 3, sm: 4 },
                             height: '100%',
                             transition: 'all 0.3s ease',
                             border: '1px solid',
                             borderColor: 'divider',
                             '&:hover': {
                               transform: { xs: 'none', md: 'translateY(-8px) scale(1.02)' },
                               boxShadow: `0 20px 25px -5px rgba(0, 206, 209, 0.15)`, // Aqua Blue shadow on hover
                               borderColor: theme.palette.secondary.main, // Orange border on hover
                             },
                           }}
                         >
                           <Box
                             sx={{
                               width: { xs: 48, sm: 56 },
                               height: { xs: 48, sm: 56 },
                               backgroundColor: `${theme.palette.primary.main}15`, // Faint Orange background
                               borderRadius: 3,
                               display: 'flex',
                               alignItems: 'center',
                               justifyContent: 'center',
                               mb: 3,
                               boxShadow: `0 4px 12px rgba(255, 153, 51, 0.15)`,
                             }}
                           >
                             <Box sx={{ color: theme.palette.primary.main }}> {/* Icon in Orange */}
                               <Icon size={28} />
                             </Box>
                           </Box>
                           <Typography
                             variant="h6"
                             sx={{
                               fontWeight: 'bold',
                               color: 'text.primary',
                               mb: 2,
                               fontSize: { xs: '1rem', sm: '1.125rem' },
                             }}
                           >
                             {feature.title}
                           </Typography>
                           <Typography
                             variant="body2"
                             sx={{
                               color: 'text.secondary',
                               lineHeight: 1.6,
                               fontSize: { xs: '0.875rem', sm: '0.95rem' },
                             }}
                           >
                             {feature.description}
                           </Typography>
                         </Card>
                       </Grid>
                     )
                   })}
                 </Grid>
               </Container>
             </Box>
    )
}